package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TComentario generated by hbm2java
 */
public class TComentario  implements java.io.Serializable {


     private int idcomentario;
    
     private TProyecto TProyecto;
     private String descripcion;
    

    public TComentario() {
    }

	
    public TComentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public TComentario(int idcomentario, TProyecto TProyecto, String descripcion) {
       this.idcomentario = idcomentario;
      
       this.TProyecto = TProyecto;
       this.descripcion = descripcion;
      
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
   
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   



}


