package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TSugerencia generated by hbm2java
 */
public class TSugerencia  implements java.io.Serializable {


     private int idsugerencia;
    
     private TProyecto TProyecto;
     private String descripcion;
     

    public TSugerencia() {
    }

	
    public TSugerencia(int idsugerencia) {
        this.idsugerencia = idsugerencia;
    }
    public TSugerencia(int idsugerencia, TProyecto TProyecto, String descripcion) {
       this.idsugerencia = idsugerencia;
     
       this.TProyecto = TProyecto;
       this.descripcion = descripcion;
      
    }
   
    public int getIdsugerencia() {
        return this.idsugerencia;
    }
    
    public void setIdsugerencia(int idsugerencia) {
        this.idsugerencia = idsugerencia;
    }
   
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    




}


